# Generated by Django 3.0.8 on 2020-09-20 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0002_auto_20200718_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annonce',
            name='date_archive',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'archivage"),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='content',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='title',
            field=models.CharField(max_length=255, verbose_name="Titre de l'annonce"),
        ),
        migrations.AlterField(
            model_name='page',
            name='abonn',
            field=models.ManyToManyField(blank=True, related_name='abonn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='page',
            name='organisme',
            field=models.CharField(blank=True, max_length=150, verbose_name="Nom de l'organisme (facultatif)"),
        ),
    ]
